// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rocket_Launch_Database__2_.Data;

#nullable disable

namespace Rocket_Launch_Database__2_.Migrations
{
    [DbContext(typeof(RocketLaunchDbContext))]
    partial class RocketLaunchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rocket_Launch_Database__2_.Models.LaunchSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LaunchSite");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "USA",
                            Name = "Site A"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Russia",
                            Name = "Site B"
                        },
                        new
                        {
                            Id = 3,
                            Location = "USA",
                            Name = "Cape Canaveral"
                        },
                        new
                        {
                            Id = 4,
                            Location = "USA",
                            Name = "Vandenberg"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Russia",
                            Name = "Plesetsk"
                        },
                        new
                        {
                            Id = 6,
                            Location = "Kazakhstan",
                            Name = "Baikonur"
                        },
                        new
                        {
                            Id = 7,
                            Location = "French Guiana",
                            Name = "Guiana Space Centre"
                        },
                        new
                        {
                            Id = 8,
                            Location = "Japan",
                            Name = "Tanegashima"
                        },
                        new
                        {
                            Id = 9,
                            Location = "India",
                            Name = "Satish Dhawan"
                        },
                        new
                        {
                            Id = 10,
                            Location = "China",
                            Name = "Jiuquan"
                        },
                        new
                        {
                            Id = 11,
                            Location = "China",
                            Name = "Taiyuan"
                        },
                        new
                        {
                            Id = 12,
                            Location = "USA",
                            Name = "Wallops Flight Facility"
                        },
                        new
                        {
                            Id = 13,
                            Location = "Marshall Islands",
                            Name = "Omelek Island"
                        },
                        new
                        {
                            Id = 14,
                            Location = "USA",
                            Name = "Kodiak Launch Complex"
                        },
                        new
                        {
                            Id = 15,
                            Location = "USA",
                            Name = "Mid-Atlantic Regional Spaceport"
                        },
                        new
                        {
                            Id = 16,
                            Location = "South Korea",
                            Name = "Naro Space Center"
                        },
                        new
                        {
                            Id = 17,
                            Location = "Israel",
                            Name = "Palmachim Airbase"
                        },
                        new
                        {
                            Id = 18,
                            Location = "North Korea",
                            Name = "Sohae Satellite Launching Station"
                        },
                        new
                        {
                            Id = 19,
                            Location = "Russia",
                            Name = "Vostochny Cosmodrome"
                        },
                        new
                        {
                            Id = 20,
                            Location = "China",
                            Name = "Wenchang Satellite Launch Center"
                        });
                });

            modelBuilder.Entity("Rocket_Launch_Database__2_.Models.LaunchVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LaunchVehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "SpaceX",
                            Name = "Falcon 9"
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "Roscosmos",
                            Name = "Soyuz"
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "ULA",
                            Name = "Atlas V"
                        },
                        new
                        {
                            Id = 4,
                            Manufacturer = "ULA",
                            Name = "Delta IV"
                        },
                        new
                        {
                            Id = 5,
                            Manufacturer = "Arianespace",
                            Name = "Ariane 5"
                        },
                        new
                        {
                            Id = 6,
                            Manufacturer = "Arianespace",
                            Name = "Vega"
                        },
                        new
                        {
                            Id = 7,
                            Manufacturer = "Mitsubishi Heavy Industries",
                            Name = "H-IIA"
                        },
                        new
                        {
                            Id = 8,
                            Manufacturer = "Mitsubishi Heavy Industries",
                            Name = "H-IIB"
                        },
                        new
                        {
                            Id = 9,
                            Manufacturer = "Northrop Grumman",
                            Name = "Antares"
                        },
                        new
                        {
                            Id = 10,
                            Manufacturer = "SpaceX",
                            Name = "Falcon Heavy"
                        },
                        new
                        {
                            Id = 11,
                            Manufacturer = "Rocket Lab",
                            Name = "Electron"
                        },
                        new
                        {
                            Id = 12,
                            Manufacturer = "Northrop Grumman",
                            Name = "Pegasus"
                        },
                        new
                        {
                            Id = 13,
                            Manufacturer = "Northrop Grumman",
                            Name = "Minotaur"
                        },
                        new
                        {
                            Id = 14,
                            Manufacturer = "Khrunichev",
                            Name = "Proton"
                        },
                        new
                        {
                            Id = 15,
                            Manufacturer = "CASC",
                            Name = "Long March 2D"
                        },
                        new
                        {
                            Id = 16,
                            Manufacturer = "CASC",
                            Name = "Long March 3B"
                        },
                        new
                        {
                            Id = 17,
                            Manufacturer = "CASC",
                            Name = "Long March 5"
                        },
                        new
                        {
                            Id = 18,
                            Manufacturer = "CASC",
                            Name = "Long March 7"
                        },
                        new
                        {
                            Id = 19,
                            Manufacturer = "Blue Origin",
                            Name = "New Shepard"
                        },
                        new
                        {
                            Id = 20,
                            Manufacturer = "SpaceX",
                            Name = "Starship"
                        });
                });

            modelBuilder.Entity("Rocket_Launch_Database__2_.Models.Payload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Payload");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Payload A",
                            Type = "Satellite",
                            Weight = 1000m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Payload B",
                            Type = "Spacecraft",
                            Weight = 2000m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Communication Satellite 1",
                            Type = "Satellite",
                            Weight = 2000m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Communication Satellite 2",
                            Type = "Satellite",
                            Weight = 1800m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Earth Observation Satellite 1",
                            Type = "Satellite",
                            Weight = 1200m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Earth Observation Satellite 2",
                            Type = "Satellite",
                            Weight = 1500m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Navigation Satellite 1",
                            Type = "Satellite",
                            Weight = 1400m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Navigation Satellite 2",
                            Type = "Satellite",
                            Weight = 1600m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Scientific Satellite 1",
                            Type = "Satellite",
                            Weight = 1300m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Scientific Satellite 2",
                            Type = "Satellite",
                            Weight = 1100m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Lunar Probe 1",
                            Type = "Probe",
                            Weight = 800m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Lunar Probe 2",
                            Type = "Probe",
                            Weight = 850m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Mars Rover 1",
                            Type = "Rover",
                            Weight = 900m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Mars Rover 2",
                            Type = "Rover",
                            Weight = 950m
                        },
                        new
                        {
                            Id = 15,
                            Name = "Space Telescope 1",
                            Type = "Telescope",
                            Weight = 2000m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Space Telescope 2",
                            Type = "Telescope",
                            Weight = 2100m
                        },
                        new
                        {
                            Id = 17,
                            Name = "Space Station Module 1",
                            Type = "Module",
                            Weight = 4200m
                        },
                        new
                        {
                            Id = 18,
                            Name = "Space Station Module 2",
                            Type = "Module",
                            Weight = 4300m
                        },
                        new
                        {
                            Id = 19,
                            Name = "Interplanetary Probe 1",
                            Type = "Probe",
                            Weight = 3000m
                        },
                        new
                        {
                            Id = 20,
                            Name = "Interplanetary Probe 2",
                            Type = "Probe",
                            Weight = 3200m
                        });
                });

            modelBuilder.Entity("Rocket_Launch_Database__2_.Models.RocketLaunch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LaunchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LaunchSiteId")
                        .HasColumnType("int");

                    b.Property<int>("LaunchVehicleId")
                        .HasColumnType("int");

                    b.Property<string>("MissionOutcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PayloadId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LaunchSiteId");

                    b.HasIndex("LaunchVehicleId");

                    b.HasIndex("PayloadId");

                    b.HasIndex("UserId");

                    b.ToTable("RocketLaunches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LaunchDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 1,
                            LaunchVehicleId = 1,
                            MissionOutcome = "Success",
                            PayloadId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            LaunchDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 2,
                            LaunchVehicleId = 2,
                            MissionOutcome = "Failure",
                            PayloadId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            LaunchDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 3,
                            LaunchVehicleId = 3,
                            MissionOutcome = "Success",
                            PayloadId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            LaunchDate = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 4,
                            LaunchVehicleId = 4,
                            MissionOutcome = "Failure",
                            PayloadId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            LaunchDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 5,
                            LaunchVehicleId = 5,
                            MissionOutcome = "Success",
                            PayloadId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            LaunchDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 6,
                            LaunchVehicleId = 6,
                            MissionOutcome = "Failure",
                            PayloadId = 6,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            LaunchDate = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 7,
                            LaunchVehicleId = 7,
                            MissionOutcome = "Success",
                            PayloadId = 7,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            LaunchDate = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 8,
                            LaunchVehicleId = 8,
                            MissionOutcome = "Failure",
                            PayloadId = 8,
                            UserId = 8
                        },
                        new
                        {
                            Id = 10,
                            LaunchDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 9,
                            LaunchVehicleId = 9,
                            MissionOutcome = "Success",
                            PayloadId = 9,
                            UserId = 9
                        },
                        new
                        {
                            Id = 9,
                            LaunchDate = new DateTime(2023, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 10,
                            LaunchVehicleId = 10,
                            MissionOutcome = "Failure",
                            PayloadId = 10,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            LaunchDate = new DateTime(2023, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 11,
                            LaunchVehicleId = 11,
                            MissionOutcome = "Success",
                            PayloadId = 11,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            LaunchDate = new DateTime(2023, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 12,
                            LaunchVehicleId = 12,
                            MissionOutcome = "Failure",
                            PayloadId = 12,
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            LaunchDate = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 13,
                            LaunchVehicleId = 13,
                            MissionOutcome = "Success",
                            PayloadId = 13,
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            LaunchDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 14,
                            LaunchVehicleId = 14,
                            MissionOutcome = "Failure",
                            PayloadId = 14,
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            LaunchDate = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 15,
                            LaunchVehicleId = 15,
                            MissionOutcome = "Success",
                            PayloadId = 15,
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            LaunchDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 16,
                            LaunchVehicleId = 16,
                            MissionOutcome = "Failure",
                            PayloadId = 16,
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            LaunchDate = new DateTime(2023, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 17,
                            LaunchVehicleId = 17,
                            MissionOutcome = "Success",
                            PayloadId = 17,
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            LaunchDate = new DateTime(2023, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 18,
                            LaunchVehicleId = 18,
                            MissionOutcome = "Failure",
                            PayloadId = 18,
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            LaunchDate = new DateTime(2023, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 19,
                            LaunchVehicleId = 19,
                            MissionOutcome = "Success",
                            PayloadId = 19,
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            LaunchDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LaunchSiteId = 20,
                            LaunchVehicleId = 20,
                            MissionOutcome = "Failure",
                            PayloadId = 20,
                            UserId = 20
                        });
                });

            modelBuilder.Entity("Rocket_Launch_Database__2_.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie@example.com",
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            Email = "david@example.com",
                            Name = "David"
                        },
                        new
                        {
                            Id = 5,
                            Email = "eve@example.com",
                            Name = "Eve"
                        },
                        new
                        {
                            Id = 6,
                            Email = "frank@example.com",
                            Name = "Frank"
                        },
                        new
                        {
                            Id = 7,
                            Email = "grace@example.com",
                            Name = "Grace"
                        },
                        new
                        {
                            Id = 8,
                            Email = "hannah@example.com",
                            Name = "Hannah"
                        },
                        new
                        {
                            Id = 9,
                            Email = "ivan@example.com",
                            Name = "Ivan"
                        },
                        new
                        {
                            Id = 10,
                            Email = "judy@example.com",
                            Name = "Judy"
                        },
                        new
                        {
                            Id = 11,
                            Email = "kevin@example.com",
                            Name = "Kevin"
                        },
                        new
                        {
                            Id = 12,
                            Email = "laura@example.com",
                            Name = "Laura"
                        },
                        new
                        {
                            Id = 13,
                            Email = "mike@example.com",
                            Name = "Mike"
                        },
                        new
                        {
                            Id = 14,
                            Email = "nina@example.com",
                            Name = "Nina"
                        },
                        new
                        {
                            Id = 15,
                            Email = "oscar@example.com",
                            Name = "Oscar"
                        },
                        new
                        {
                            Id = 16,
                            Email = "pam@example.com",
                            Name = "Pam"
                        },
                        new
                        {
                            Id = 17,
                            Email = "quinn@example.com",
                            Name = "Quinn"
                        },
                        new
                        {
                            Id = 18,
                            Email = "rob@example.com",
                            Name = "Rob"
                        },
                        new
                        {
                            Id = 19,
                            Email = "sara@example.com",
                            Name = "Sara"
                        },
                        new
                        {
                            Id = 20,
                            Email = "tom@example.com",
                            Name = "Tom"
                        });
                });

            modelBuilder.Entity("Rocket_Launch_Database__2_.Models.RocketLaunch", b =>
                {
                    b.HasOne("Rocket_Launch_Database__2_.Models.LaunchSite", "LaunchSite")
                        .WithMany()
                        .HasForeignKey("LaunchSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rocket_Launch_Database__2_.Models.LaunchVehicle", "LaunchVehicle")
                        .WithMany()
                        .HasForeignKey("LaunchVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rocket_Launch_Database__2_.Models.Payload", "Payload")
                        .WithMany()
                        .HasForeignKey("PayloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rocket_Launch_Database__2_.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaunchSite");

                    b.Navigation("LaunchVehicle");

                    b.Navigation("Payload");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
